/**
 * Building type definitions
 */
export const BUILDING_TYPES = {
  hq: {
    type: 'hq',
    name: '指揮中心',
    size: 32,
    maxHp: 1500,
    cost: { crystal: 0, gas: 0 },
    buildTime: 0,
    produces: ['worker'],
    providesSupply: 10,
  },
  barracks: {
    type: 'barracks',
    name: '軍營',
    size: 28,
    maxHp: 800,
    cost: { crystal: 150, gas: 0 },
    buildTime: 20,
    produces: ['soldier'],
    providesSupply: 0,
  },
  factory: {
    type: 'factory',
    name: '重工廠',
    size: 36,
    maxHp: 1200,
    cost: { crystal: 300, gas: 150 },
    buildTime: 30,
    produces: ['tank'],
    providesSupply: 0,
  },
  starport: {
    type: 'starport',
    name: '星港',
    size: 36,
    maxHp: 1000,
    cost: { crystal: 250, gas: 200 },
    buildTime: 28,
    produces: ['flyer'],
    providesSupply: 0,
  },
  refinery: {
    type: 'refinery',
    name: '精煉廠',
    size: 24,
    maxHp: 600,
    cost: { crystal: 100, gas: 0 },
    buildTime: 15,
    produces: [],
    providesSupply: 0,
    refinesGas: true,
  },
  supply: {
    type: 'supply',
    name: '補給站',
    size: 20,
    maxHp: 400,
    cost: { crystal: 100, gas: 0 },
    buildTime: 15,
    produces: [],
    providesSupply: 8,
  },
  turret: {
    type: 'turret',
    name: '防禦砲塔',
    size: 16,
    maxHp: 500,
    cost: { crystal: 100, gas: 50 },
    buildTime: 12,
    produces: [],
    providesSupply: 0,
    attackDamage: 25,
    attackRange: 180,
    attackCooldown: 1.2,
  },
};
