/**
 * Unit type definitions
 */
export const UNIT_TYPES = {
  worker: {
    type: 'worker',
    name: '工程兵',
    size: 8,
    maxHp: 50,
    speed: 60,
    attackDamage: 5,
    attackRange: 30,
    attackCooldown: 1.5,
    cost: { crystal: 50, gas: 0 },
    buildTime: 8,
    canHarvest: true,
    canBuild: true,
    harvestAmount: 8,
    harvestTime: 2,
  },
  soldier: {
    type: 'soldier',
    name: '突擊兵',
    size: 10,
    maxHp: 100,
    speed: 55,
    attackDamage: 15,
    attackRange: 120,
    attackCooldown: 0.8,
    cost: { crystal: 100, gas: 0 },
    buildTime: 12,
    canHarvest: false,
    canBuild: false,
  },
  tank: {
    type: 'tank',
    name: '重甲戰車',
    size: 16,
    maxHp: 300,
    speed: 35,
    attackDamage: 40,
    attackRange: 160,
    attackCooldown: 2.0,
    cost: { crystal: 200, gas: 100 },
    buildTime: 20,
    canHarvest: false,
    canBuild: false,
    splashRadius: 30,
  },
  flyer: {
    type: 'flyer',
    name: '戰鬥機',
    size: 12,
    maxHp: 120,
    speed: 90,
    attackDamage: 20,
    attackRange: 100,
    attackCooldown: 1.0,
    cost: { crystal: 150, gas: 150 },
    buildTime: 18,
    canHarvest: false,
    canBuild: false,
    flying: true,
  },
};
